apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ckn-gcp-sc
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  replication-type: none
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer