apiVersion: v1
kind: Service
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: ck-postgres
    role: primary
