apiVersion: v1
kind: Service
metadata:
  name: ck-postgres
  namespace: codekarma
spec:
  clusterIP: None
  selector:
    app: ck-postgres
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql