{{- /* Create a StorageClass from Postgres values if requested. */ -}}
{{- if .Values.persistence.createStorageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass | quote }}
  {{- if .Values.persistence.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.persistence.provisioner | default "ebs.csi.eks.amazonaws.com" }}
{{- if .Values.persistence.reclaimPolicy }}
reclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
{{- end }}
volumeBindingMode: {{ .Values.persistence.volumeBindingMode | default "WaitForFirstConsumer" }}
parameters:
{{- if .Values.persistence.parameters }}
{{- range $k, $v := .Values.persistence.parameters }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- else }}
  {}
{{- end }}
---
{{- end }}
