# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgresql-custom-config
#   namespace: codekarma
# data:
#   WAL_GS_BUCKET: "ck-flipkart-pg-storage-bucket"
#   AWS_S3_FORCE_PATH_STYLE: "true"
#   USE_WALG_BACKUP: "true"
#   USE_WALG_RESTORE: "true"
#   CLONE_USE_WALG_RESTORE: "true"