apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ck-nexus-app
  namespace: {{ .Release.Namespace }}
  labels:
    release: ckp
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: ck-nexus-app
      job: ck-nexus-app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: "/actuator/prometheus"
      interval: 30s