apiVersion: v1
kind: Service
metadata:
  name: ck-nexus-app
  labels:
    app: ck-nexus-app
    job: ck-nexus-app
  {{- if .Values.nexus_service.annotations }}
  annotations:
    {{- range $key, $value := .Values.nexus_service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.nexus_service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.nexus_service.port }}
      targetPort: {{ .Values.nexus_service.port }}
      {{- if and (eq (.Values.nexus_service.type | default "ClusterIP") "LoadBalancer") (.Values.nexus_service.nodePort) }}
      nodePort: {{ .Values.nexus_service.nodePort }}
      {{- end }}
  selector:
    app: ck-nexus-app

