apiVersion: v2
name: karma-lens
description: A Helm chart for Karma Lens application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - karma-lens
  - monitoring
  - visualization
home: https://github.com/codekarma-tech/karma-lens.git 
sources:
  - https://github.com/codekarma-tech/karma-lens.git 